### PR TITLE
Fixed occasional macOS build failures due to Python

### LINKED ISSUE #31: Fix occasional brew install failures due to Python 3.12 dependency
## Summary

Occasionally the macOS job fails due to Python 3.12 dependency as shown by the log below,

```zsh
  ==> Installing osrf/simulation/gz-harmonic dependency: python@3.12
  ==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.4
  Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/2970a992f26f411cf71250ce54eb24411d8b065824b51819da7085559f09ce66--python@3.12-3.12.4.bottle_manifest.json
  ==> Pouring python@3.12--3.12.4.ventura.bottle.tar.gz
  Error: The `brew link` step did not complete successfully
  Error: The `brew link` step did not complete successfully
  The formula built, but is not symlinked into /usr/local
  Could not symlink bin/2to3
  Target /usr/local/bin/2to3
  already exists. You may want to remove it:
    rm '/usr/local/bin/2to3'
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite python@3.12
  
  To list all files that would be deleted:
    brew link --overwrite python@3.12 --dry-run
  
  Possible conflicting files are:
  /usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/2to3
  /usr/local/bin/2to3-3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/2to3-3.12
  /usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/idle3
  /usr/local/bin/idle3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/idle3.12
  /usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/pydoc3
  /usr/local/bin/pydoc3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/pydoc3.12
  /usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
  /usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3-config
  /usr/local/bin/python3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12
  /usr/local/bin/python3.12-config -> /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12-config
```

## Proposed fix

Referring to a related issue - https://github.com/Homebrew/homebrew-core/issues/165793.
The proposed fix would be to delete the existing Python installation and force install the preferred version.

### PR DESCRIPTION
**Pull request by sauk2**
Closes #31 

This PR is meant to fix the occasional Python brew link failures by force installing and relinking Python.

### CODE REVIEW

File: src/setup-gazebo-macos.ts [hunk 1]
```diff
@@ -4,16 +4,34 @@ import * as brew from "./package_manager/brew";
 /**
  * Tap into OSRF repository
  */
-async function addBrewRepo() {
+async function addBrewRepo(): Promise<void> {
 	await utils.exec("brew", ["tap", "osrf/simulation"]);
 }
 
+/**
+ * Overwrite existing python installation
```
Comment (j-rivero) [inline src/setup-gazebo-macos.ts:12]: Could we please add here a comment with the reasoning of making this uninstall / install special steps.

**Review by j-rivero — APPROVED** [review]
A side from the comment, looks good!

**Comment by sauk2** [comment]
I have added a comment about that error. This PR is ready to be merged :tada:
